In [1]:
using Random
using Combinatorics
using Plots

In [2]:
function rank2matrix(rank)
    N = length(rank)
    n = Int((1 + sqrt(1 + 8N)) / 2)
    S = zeros(Int,n,n)        

    k = 1
    for i = 1:n
        for j = i+1:n
            S[i,j] = rank[k]
            S[j,i] = rank[k]
            k = k + 1
        end
    end
    return S
end

rank2matrix (generic function with 1 method)

In [3]:
n = 5
m = 3
X = [i for i=1:n]
L = shuffle!(cat(collect(1:m), rand(1:m, n-m), dims=1))
N = Int(n*(n-1)/2)

println("n = $n\nm = $m\nN = $N")
println("L = $L")

n = 5
m = 3
N = 10
L = [2, 1, 1, 3, 2]


In [4]:
rank = shuffle(1:N)
println("pairs ranking = $rank\n S=")
S = rank2matrix(rank)
display(S)

Q = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if S[i,j] < S[p,q]]
R = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if L[p] == L[q] && L[i] != L[j]]

r = [sum(L.==k) for k in 1:m]
shareL = sum(r .* (r .- 1) /2)
maxQR = (N - shareL) * shareL

length(intersect(Q,R))/maxQR

pairs ranking = [3, 5, 10, 9, 4, 6, 1, 2, 7, 8]
 S=


5×5 Matrix{Int64}:
  0  3  5  10  9
  3  0  4   6  1
  5  4  0   2  7
 10  6  2   0  8
  9  1  7   8  0

0.625

In [ ]:
r = [sum(L.==k) for k in 1:m]
shareL = sum(r .* (r .- 1) /2)
maxQR = (N - shareL) * shareL

Γs = zeros(factorial(N))
for k = 1:factorial(N)
    rank = nthperm(1:N, k)
    S = rank2matrix(rank)
    
    Q = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if S[i,j] < S[p,q]]
    R = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if L[p] == L[q] && L[i] != L[j]]
    
    Γs[k] = length(intersect(Q,R))/maxQR
    if mod(k,100000)==0
        print(".  ")
    end 
end

.  .  .  .  .  .  .  

In [ ]:
u = sort(unique(Γs))
println(u)
u[2:end] - u[1:end-1]

In [5]:
# Ejemplo: siempre se puede alcanzar el minimo para algun S
n = 15
m = 4
X = [i for i=1:n]
L = shuffle!(cat(collect(1:m), rand(1:m, n-m), dims=1))
N = Int(n*(n-1)/2)

r = [sum(L.==k) for k in 1:m]
shareL = sum(r .* (r .- 1) /2)
maxQR = (N - shareL) * shareL

println("n = $n\nm = $m\nN = $N")
println("L = $L")


S = zeros(Int,n,n)       
k = 1
kk = N
for i=1:n
    for j=i+1:n
        if L[i] == L[j]
            S[i,j] = k
            S[j,i] = k
            k = k + 1
        else
            S[i,j] = kk
            S[j,i] = kk
            kk = kk - 1
        end
    end
end
display(S)

Q = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if S[i,j] < S[p,q]]
R = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if L[p] == L[q] && L[i] != L[j]]


length(intersect(Q,R))/maxQR

n = 15
m = 4
N = 105
L = [1, 1, 2, 2, 1, 2, 4, 1, 3, 4, 4, 2, 2, 3, 4]


15×15 Matrix{Int64}:
   0   1  105  104   2  103  102   3  101  100  99  98  97  96  95
   1   0   94   93   4   92   91   5   90   89  88  87  86  85  84
 105  94    0    6  83    7   82  81   80   79  78   8   9  77  76
 104  93    6    0  75   10   74  73   72   71  70  11  12  69  68
   2   4   83   75   0   67   66  13   65   64  63  62  61  60  59
 103  92    7   10  67    0   58  57   56   55  54  14  15  53  52
 102  91   82   74  66   58    0  51   50   16  17  49  48  47  18
   3   5   81   73  13   57   51   0   46   45  44  43  42  41  40
 101  90   80   72  65   56   50  46    0   39  38  37  36  19  35
 100  89   79   71  64   55   16  45   39    0  20  34  33  32  21
  99  88   78   70  63   54   17  44   38   20   0  31  30  29  22
  98  87    8   11  62   14   49  43   37   34  31   0  23  28  27
  97  86    9   12  61   15   48  42   36   33  30  23   0  26  25
  96  85   77   69  60   53   47  41   19   32  29  28  26   0  24
  95  84   76   68  59   52   18  40   35

0.0

In [6]:
# Ejemplo: siempre se puede alcanzar el minimo para algun S
n = 15
m = 4
X = [i for i=1:n]
L = shuffle!(cat(collect(1:m), rand(1:m, n-m), dims=1))
N = Int(n*(n-1)/2)

r = [sum(L.==k) for k in 1:m]
shareL = sum(r .* (r .- 1) /2)
maxQR = (N - shareL) * shareL

println("n = $n\nm = $m\nN = $N")
println("L = $L")


rank = shuffle(1:N)
S = rank2matrix(rank)
display(S)

Q = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if S[i,j] < S[p,q]]
R = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if L[p] == L[q] && L[i] != L[j]]


Γ = length(intersect(Q,R))/maxQR
γ = 1-2Γ

println("Γ = $Γ\nγ = $γ")

s_pluss = sum([1 for i=1:n for j=i+1:n for p=1:n for q=p+1:n if L[p] == L[q] && L[i] != L[j] && S[i,j] > S[p,q]])
s_minus = sum([1 for i=1:n for j=i+1:n for p=1:n for q=p+1:n if L[p] == L[q] && L[i] != L[j] && S[i,j] < S[p,q]])
(s_pluss - s_minus) / (s_pluss + s_minus)

n = 15
m = 4
N = 105
L = [3, 1, 3, 3, 2, 1, 4, 1, 1, 1, 2, 2, 2, 4, 4]


15×15 Matrix{Int64}:
  0   54  36  91   32  84  67   23   95  35   98   59  87  42   34
 54    0   7  82   16  92  61    9   76  10  103   77  12  31   30
 36    7   0  79   39   8  70   53   49  66   21   57  43  52   37
 91   82  79   0   63  18  97   64   71   5   65   68  93  73   96
 32   16  39  63    0  90  11    3  101  83   51  102  78  29   38
 84   92   8  18   90   0  28   25    6  17   55   44  48  14   74
 67   61  70  97   11  28   0   60   56  80   24   19  58  75   89
 23    9  53  64    3  25  60    0   99  50   46  104  47   2   45
 95   76  49  71  101   6  56   99    0  20   27   26  69   1   85
 35   10  66   5   83  17  80   50   20   0   81   88  94  13   72
 98  103  21  65   51  55  24   46   27  81    0  100  86  15   62
 59   77  57  68  102  44  19  104   26  88  100    0  40  41  105
 87   12  43  93   78  48  58   47   69  94   86   40   0   4   33
 42   31  52  73   29  14  75    2    1  13   15   41   4   0   22
 34   30  37  96   38  74  89   45   85  

Γ = 0.547645125958379
γ = -0.095290251916758


-0.09529025191675794

In [9]:
using LinearAlgebra
function gammaindex(
        assignments::Vector{<:Int},
        dist::Matrix{<:Real}
    )
    issymmetric(dist) || throw(ArgumentError("Distance Matrix is not symmetric"))
    
    n = length(assignments)
    n == size(dist)[1] || throw(DimensionMismatch("Distance Matrix and assignments dimension mismatch"))
    
    k = length(unique(assignments))
    1:k == sort(unique(assignments)) || throw(ArgumentError("assignments vector is not of consecutive integer values"))
    
    s_pluss = 0
    s_minus = 0
    for i = 1:n
        for j = i+1:n
            for p=1:n 
                for q=p+1:n
                    if assignments[p] == assignments[q]  && assignments[i] != assignments[j]
                        if dist[i,j] > dist[p,q]
                            s_pluss = s_pluss + 1 
                        elseif dist[i,j] < dist[p,q]
                            s_minus = s_minus + 1
                        end
                    end
                end
            end
        end
    end
    
    ΓI = (s_pluss - s_minus) / (s_pluss + s_minus)
    return ΓI     
end

gammaindex(L,S)

-0.09529025191675794