In [1]:
using Random
using Combinatorics
using Plots

In [2]:
function rank2matrix(rank)
    N = length(rank)
    n = Int((1 + sqrt(1 + 8N)) / 2)
    S = zeros(Int,n,n)        

    k = 1
    for i = 1:n
        for j = i+1:n
            S[i,j] = rank[k]
            S[j,i] = rank[k]
            k = k + 1
        end
    end
    return S
end

rank2matrix (generic function with 1 method)

In [3]:
n = 5
m = 3
X = [i for i=1:n]
L = shuffle!(cat(collect(1:m), rand(1:m, n-m), dims=1))
N = Int(n*(n-1)/2)

println("n = $n\nm = $m\nN = $N")
println("L = $L")

n = 5
m = 3
N = 10
L = [3, 3, 2, 1, 2]


In [4]:
rank = shuffle(1:N)
println("pairs ranking = $rank\n S=")
S = rank2matrix(rank)
display(S)

Q = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if S[i,j] < S[p,q]]
R = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if L[p] == L[q] && L[i] != L[j]]

r = [sum(L.==k) for k in 1:m]
shareL = sum(r .* (r .- 1) /2)
maxQR = (N - shareL) * shareL

length(intersect(Q,R))/maxQR

pairs ranking = [8, 7, 6, 2, 10, 9, 3, 4, 1, 5]
 S=


5×5 Matrix{Int64}:
 0   8   7  6  2
 8   0  10  9  3
 7  10   0  4  1
 6   9   4  0  5
 2   3   1  5  0

0.375

In [15]:
r = [sum(L.==k) for k in 1:m]
shareL = sum(r .* (r .- 1) /2)
maxQR = (N - shareL) * shareL

Γs = zeros(factorial(N))
for k = 1:factorial(N)
    rank = nthperm(1:N, k)
    S = rank2matrix(rank)
    
    Q = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if S[i,j] < S[p,q]]
    R = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if L[p] == L[q] && L[i] != L[j]]
    
    Γs[k] = length(intersect(Q,R))/maxQR
    if mod(k,100000)==0
        print(".  ")
    end 
end

.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  

In [24]:
u = sort(unique(Γs))
println(u)
u[2:end] - u[1:end-1]

[0.0, 0.0625, 0.125, 0.1875, 0.25, 0.3125, 0.375, 0.4375, 0.5, 0.5625, 0.625, 0.6875, 0.75, 0.8125, 0.875, 0.9375, 1.0]


16-element Vector{Float64}:
 0.0625
 0.0625
 0.0625
 0.0625
 0.0625
 0.0625
 0.0625
 0.0625
 0.0625
 0.0625
 0.0625
 0.0625
 0.0625
 0.0625
 0.0625
 0.0625

In [9]:
# Ejemplo: siempre se puede alcanzar el minimo para algun S
n = 15
m = 4
X = [i for i=1:n]
L = shuffle!(cat(collect(1:m), rand(1:m, n-m), dims=1))
N = Int(n*(n-1)/2)

r = [sum(L.==k) for k in 1:m]
shareL = sum(r .* (r .- 1) /2)
maxQR = (N - shareL) * shareL

println("n = $n\nm = $m\nN = $N")
println("L = $L")


S = zeros(Int,n,n)       
k = 1
kk = N
for i=1:n
    for j=i+1:n
        if L[i] == L[j]
            S[i,j] = k
            S[j,i] = k
            k = k + 1
        else
            S[i,j] = kk
            S[j,i] = kk
            kk = kk - 1
        end
    end
end
display(S)

Q = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if S[i,j] < S[p,q]]
R = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if L[p] == L[q] && L[i] != L[j]]


length(intersect(Q,R))/maxQR

n = 15
m = 4
N = 105
L = [2, 4, 2, 4, 4, 1, 1, 3, 3, 1, 2, 2, 4, 2, 1]


15×15 Matrix{Int64}:
   0  105   1  104  103  102  101  100  99  98   2   3  97   4  96
 105    0  95    5    6   94   93   92  91  90  89  88   7  87  86
   1   95   0   85   84   83   82   81  80  79   8   9  78  10  77
 104    5  85    0   11   76   75   74  73  72  71  70  12  69  68
 103    6  84   11    0   67   66   65  64  63  62  61  13  60  59
 102   94  83   76   67    0   14   58  57  15  56  55  54  53  16
 101   93  82   75   66   14    0   52  51  17  50  49  48  47  18
 100   92  81   74   65   58   52    0  19  46  45  44  43  42  41
  99   91  80   73   64   57   51   19   0  40  39  38  37  36  35
  98   90  79   72   63   15   17   46  40   0  34  33  32  31  20
   2   89   8   71   62   56   50   45  39  34   0  21  30  22  29
   3   88   9   70   61   55   49   44  38  33  21   0  28  23  27
  97    7  78   12   13   54   48   43  37  32  30  28   0  26  25
   4   87  10   69   60   53   47   42  36  31  22  23  26   0  24
  96   86  77   68   59   16   18   41  3

0.0

In [29]:
# Ejemplo: siempre se puede alcanzar el minimo para algun S
n = 15
m = 4
X = [i for i=1:n]
L = shuffle!(cat(collect(1:m), rand(1:m, n-m), dims=1))
N = Int(n*(n-1)/2)

r = [sum(L.==k) for k in 1:m]
shareL = sum(r .* (r .- 1) /2)
maxQR = (N - shareL) * shareL

println("n = $n\nm = $m\nN = $N")
println("L = $L")


rank = shuffle(1:N)
S = rank2matrix(rank)
display(S)

Q = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if S[i,j] < S[p,q]]
R = [[i,j,p,q] for i=1:n for j=i+1:n for p=1:n for q=p+1:n if L[p] == L[q] && L[i] != L[j]]


Γ = length(intersect(Q,R))/maxQR
γ = 1-2Γ

println("Γ = $Γ\nγ = $γ")

s_pluss = sum([1 for i=1:n for j=i+1:n for p=1:n for q=p+1:n if L[p] == L[q] && L[i] != L[j] && S[i,j] > S[p,q]])
s_minus = sum([1 for i=1:n for j=i+1:n for p=1:n for q=p+1:n if L[p] == L[q] && L[i] != L[j] && S[i,j] < S[p,q]])
(s_pluss - s_minus) / (s_pluss + s_minus)

n = 15
m = 4
N = 105
L = [3, 3, 1, 3, 2, 3, 2, 3, 1, 3, 3, 2, 1, 4, 3]


15×15 Matrix{Int64}:
   0   37  104   88   1  15  18  73  105  16  68   51   28   8  41
  37    0   33   14  45  56  90  97   89  76  13   12  101  60  78
 104   33    0    9  50  96  67  26   79  95  36   22  100  72  48
  88   14    9    0  94  87  38  57   39  77  69  102  103  64  32
   1   45   50   94   0  25  10  54   52  75  53   99   11  29   2
  15   56   96   87  25   0  86  74   70  62  31   42   85  84  63
  18   90   67   38  10  86   0   5   82   3  47   20   92  93  27
  73   97   26   57  54  74   5   0   61  23  58   40   81  34  30
 105   89   79   39  52  70  82  61    0  66  46   59   35  55   6
  16   76   95   77  75  62   3  23   66   0  83   17   71  91   7
  68   13   36   69  53  31  47  58   46  83   0   65   21  24  49
  51   12   22  102  99  42  20  40   59  17  65    0   80   4  44
  28  101  100  103  11  85  92  81   35  71  21   80    0  43  19
   8   60   72   64  29  84  93  34   55  91  24    4   43   0  98
  41   78   48   32   2  63  27  30    6 

Γ = 0.5062137531068766
γ = -0.012427506213753103


-0.012427506213753107